name: GCP Deploy

# on:
#   push:
#     branches:
#       - staging
#       - main # Deploy to production when pushing to main

on: [push]

jobs:
  build-staging:
    if: github.ref == 'refs/heads/staging' # Trigger only on staging branch
    runs-on: ubuntu-latest
    name: Build and Deploy to Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_KEYFILE }}' # Use the same credentials for both environments

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: containerization-431907 # Same GCP project for both environments

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image (Staging)
        run: |
          docker build -t mapster-cloud-staging:latest .
          docker tag mapster-cloud-staging:latest gcr.io/containerization-431907/mapster-cloud-staging:latest
          docker push gcr.io/containerization-431907/mapster-cloud-staging:latest

      - name: Deploy to Cloud Run (Staging)
        run: |
          gcloud run deploy mapster-service-staging \
            --image gcr.io/containerization-431907/mapster-cloud-staging:latest \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}

  build-production:
    if: github.ref == 'refs/heads/main' # Trigger only on main branch
    runs-on: ubuntu-latest
    name: Build and Deploy to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_KEYFILE }}' # Same credentials for production

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: containerization-431907 # Same GCP project ID for production

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image (Production)
        run: |
          docker build -t mapster-cloud-prod:latest .
          docker tag mapster-cloud-prod:latest gcr.io/containerization-431907/mapster-cloud-prod:latest
          docker push gcr.io/containerization-431907/mapster-cloud-prod:latest

      - name: Deploy to Cloud Run (Production)
        run: |
          gcloud run deploy mapster-service-prod \
            --image gcr.io/containerization-431907/mapster-cloud-prod:latest \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}
