name: GCP Deploy

# on:
#   push:
#     branches:
#       - main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_KEYFILE }}
          project_id: containerization-431907

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t mapster-cloud:latest .
          docker tag mapster-cloud:latest gcr.io/containerization-431907/mapster-cloud:latest
          docker push gcr.io/containerization-431907/mapster-cloud:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mapster-service \
            --image gcr.io/containerization-431907/mapster-cloud:latest \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated
